// Generated by Lasy AI - https://lasy.ai
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
// Import all available fonts for AI usage
import "../lib/fonts";
import { LanguageProvider } from "@/contexts/LanguageContext";
import { Navigation } from "@/components/layout/Navigation";
import { FloatingAIChat } from "@/components/chat/FloatingAIChat";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "DCM VEXO - The Aesthetic-Performance OS",
  description: "Personalized AI workouts, nutrition, and performance tracking",
  manifest: "/manifest.json",
  themeColor: "#00bcd4",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark" suppressHydrationWarning>
      <head>
        <Script src="/lasy-bridge.js" strategy="beforeInteractive" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black text-white`}
        suppressHydrationWarning
      >
        <LanguageProvider>
          <Navigation />
          <main className="relative">
            {children}
          </main>
          <FloatingAIChat />
        </LanguageProvider>
      </body>
    </html>
  );
}